### ISSUE TITLE
Greetings

### ISSUE THREAD

**Issue by ArjixWasTaken** [jorgenpt/bichrome#19]
Your repository conveniently has all the code I needed to register my program as a browser, so I decided to fork it and use it as my starting line.

[Here](https://github.com/ArjixWasTaken/osu-directer) is my fork, I made sure to properly credit you and I decided to stick with just the MIT licence.

I just wanted to ask if you have any issues of me doing so.
I have removed all the branding, only your name, a link to the original repo and your email are left.

**Comment by ArjixWasTaken** [comment]
PS: I am a beginner in the rust programming language, so please don't kill me for my bad code ;-;

**Comment by jorgenpt** [comment]
@ArjixWasTaken Absolutely OK, I appreciate the crediting! It seems like something that might be easier to implement as a browser extension instead of a full browser replacement, but I'm happy to have my code used as a basis for your work. :)

Let me know if you have any questions about any of the code in bichrome!

**Comment by ArjixWasTaken** [comment]
Awesome!!


I assume you don't know what osu is, so I'll explain why I'm doing this and not a browser extension.

Basically, osu is a music game, and you can play beatmaps in it.

The game has multiplayer, and if you don't have a beatmap it launches the browser so that you can download it.

I wanted to make a browser proxy, if it is given a beatmap link then it will download the beatmap w/o the need for a browser.

If the link is not a beatmap, then it passes the link to a browser like normal.

**Comment by jorgenpt** [comment]
Ah, that's reasonable! Looks like osu is [open source](https://github.com/ppy/osu/), wouldn't it be easier to send a pull request to the game itself? :)

**Comment by ArjixWasTaken** [comment]
osu!lazer is open source, osu!stable is not

osu!lazer is going to replace osu!stable at some point

**Comment by ArjixWasTaken** [comment]
Also, my program is useless for osu!lazer, that is because it downloads them in-game

**Comment by jorgenpt** [comment]
Aah, understandable workaround then!
